Answers/3/MovieGraph.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieGraph.Web.Model;
using Neo4j.Driver.V1;

namespace MovieGraph.Web.Controllers
{
    [Route("")]
    public class HomeController : Controller
    {
        private readonly IDriver driver;

        public HomeController(IDriver driver)
        {
            this.driver = driver;
        }

        [Route("")]
        public async Task<IActionResult> Index(string q, Order order)
        {
            return View("Index", await MatchMovies(q, order));
        }

        private async Task<IEnumerable<MovieModel>> MatchMovies(string term, Order order)
        {
            if (string.IsNullOrEmpty(term))
            {
                return Enumerable.Empty<MovieModel>();
            }

            string query;
            switch (order)
            {
                case Order.MostRecentFirst:
                    query =
                        "MATCH (movie:Movie) WHERE toLower(movie.title) " +
                        "CONTAINS toLower($term) " +
                        "RETURN movie ORDER BY movie.released DESCENDING";
                    break;
                case Order.MostPopularFirst:
                    query =
                        "MATCH (movie:Movie) WHERE toLower(movie.title) " +
                        "CONTAINS toLower($term) " +
                        "RETURN movie ORDER BY coalesce(movie.stars, 0) DESCENDING";
                    break;
                case Order.Alphabetically:
                    query =
                        "MATCH (movie:Movie) WHERE toLower(movie.title) " +
                        "CONTAINS toLower($term) " +
                        "RETURN movie ORDER BY movie.title ASCENDING";

                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(order), order, null);
            }

            var session = driver.Session();
            try
            {
                return await session.ReadTransactionAsync(async tx =>
                {
                    var cursor =
                        await tx.RunAsync(
                            query,
                            new {term});

                    return await cursor.ToListAsync(record => new MovieModel(record));
                });
            }
            finally
            {
                if (session != null)
                {
                    await session.CloseAsync();
                }
            }
        }
    }
}

Answers/3/MovieGraph.Web/Controllers/MovieController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieGraph.Web.Model;
using Neo4j.Driver.V1;

namespace MovieGraph.Web.Controllers
{
    [Route("movie")]
    public class MovieController : Controller
    {
        private readonly IDriver driver;

        public MovieController(IDriver driver)
        {
            this.driver = driver;
        }

        [Route("{id}")]
        public async Task<IActionResult> Index(string id)
        {
            var movie = await MatchMovie(id);
            if (movie == null)
            {
                return StatusCode(404);
            }

            return View("Index", movie);
        }

        [Route("{id}")]
        [HttpPost]
        public async Task<IActionResult> SetStars(string id, int stars)
        {
            await SetMovieStars(id, stars);

            return RedirectToAction("Index");
        }

        private async Task<MovieModel> MatchMovie(string title)
        {
            var session = driver.Session();
            try
            {
                return await session.ReadTransactionAsync(async tx =>
                {
                    var cursor =
                        await tx.RunAsync(
                            "MATCH (movie:Movie) WHERE movie.title = $title " +
                            "OPTIONAL MATCH(person) -[:ACTED_IN]->(movie) " +
                            "RETURN movie, collect(person) AS actors",
                            new {title});

                    return new MovieModel(await cursor.SingleAsync());
                });
            }
            finally
            {
                if (session != null)
                {
                    await session.CloseAsync();
                }
            }
        }

        private async Task SetMovieStars(string title, int stars)
        {
            var session = driver.Session();
            try
            {
                await session.WriteTransactionAsync(tx =>
                    tx.RunAsync("MATCH (movie:Movie) WHERE movie.title = $title " +
                                "SET movie.stars = $stars",
                        new {title, stars})
                );
            }
            finally
            {
                if (session != null)
                {
                    await session.CloseAsync();
                }
            }
        }
    }
}

Answers/3/MovieGraph.Web/Controllers/PersonController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MovieGraph.Web.Model;
using Neo4j.Driver.V1;

namespace MovieGraph.Web.Controllers
{
    [Route("person")]
    public class PersonController : Controller
    {
        private readonly IDriver driver;

        public PersonController(IDriver driver)
        {
            this.driver = driver;
        }

        [Route("{id}")]
        public async Task<IActionResult> Index(string id)
        {
            var person = await MatchPerson(id);
            if (person == null)
            {
                return StatusCode(404);
            }

            return View("Index", person);
        }

        private async Task<PersonModel> MatchPerson(string name)
        {
            var session = driver.Session();
            try
            {
                return await session.ReadTransactionAsync(async tx =>
                {
                    var cursor =
                        await tx.RunAsync(
                            "MATCH (person:Person) WHERE person.name = $name " +
                            "OPTIONAL MATCH (person)-[:ACTED_IN]->(movie) " +
                            "RETURN person, collect(movie) AS movies",
                            new {name});

                    return new PersonModel(await cursor.SingleAsync());
                });
            }
            finally
            {
                if (session != null)
                {
                    await session.CloseAsync();
                }
            }
        }
    }
}

Answers/3/MovieGraph.Web/Views/Home/DisplayTemplates/MovieModel.cshtml
@model MovieModel

<div class="movie-summary">
    <h1 class="movie-title">
        <a href="@Url.Action("Index", "Movie", new {id = Model.Title})">@Model.Title (@Model.Released)</a>
    </h1>
    <p class="movie-tagline">@Model.Tagline</p>

    @Html.DisplayFor(m => m.Stars, "Stars")
</div>

Answers/3/MovieGraph.Web/Views/Home/DisplayTemplates/Stars.cshtml
@model int

<div class="movie-stars">
    @foreach (var star in Enumerable.Range(1, 5))
    {
        <span class="movie-star">
            @if (Model < star)
            {
                Output.Write("&#x2606;");
            }
            else
            {
                Output.Write("&#x2605;");
            }
        </span>
    }
</div>

Answers/3/MovieGraph.Web/Views/Home/Index.cshtml
@model IEnumerable<MovieModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="movie-list">
    @Html.DisplayFor(m => m)
</div>

Answers/3/MovieGraph.Web/Views/Movie/DisplayTemplates/PersonModel.cshtml
@model PersonModel

<li>
    <a href="@Url.Action("Index", "Person", new {id = Model.Name})">@Model.Name</a>
</li>

Answers/3/MovieGraph.Web/Views/Movie/Index.cshtml
@model MovieModel

@{
    ViewData["Title"] = $"{Model.Title} - Moviegraph";
}

<h1>@Model.Title (@Model.Released)</h1>
<p class="movie-tagline">@Model.Tagline</p>

@Html.EditorFor(m => m.Stars, "Stars")

<div class="movie-cast">
    <h2>Cast</h2>
    <ul>
        @Html.DisplayFor(m => m.Actors)
    </ul>
</div>

Answers/3/MovieGraph.Web/Views/Person/DisplayTemplates/MovieModel.cshtml
@model MovieModel

<li>
    <a href="@Url.Action("Index", "Movie", new {id = Model.Title})">@Model.Title (@Model.Released)</a>
</li>

Answers/3/MovieGraph.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Moviegraph</title>
    <link href="~/css/movie.css" rel="stylesheet" type="text/css">
</head>

<body>

<header>

    <form class="movie-search" action="@Url.Action("Index", "Home")">
        <h1>
            <a href="/">Moviegraph</a>
        </h1>
        <input name="q" value="@Context.Request.Query["q"]" type="text" placeholder="Search" aria-label="Search">
        <button>&#x1F50D;</button>
        @Html.DropDownList("order", Html.GetEnumSelectList<Order>())
    </form>

</header>

<main>

    @RenderBody()

</main>

</body>

</html>